const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const postcss = require('postcss');
const selectorParser = require('postcss-selector-parser');
const prefix = 'body.annie-site .elementor';

function scopeSelector(value) {
  return selectorParser(root => root.each(selector => {
    const first = selector.nodes.find(n => n.type !== 'comment');
    // Keep custom-property roots and their pseudo-classes on the document root.
    if (first?.type === 'pseudo' && first.value === ':root') return;
    if (first?.type === 'tag' && ['html', 'body'].includes(first.value.toLowerCase())) {
      first.value = 'body';
      selector.insertAfter(first, selectorParser.className({value: 'annie-site'}));
      // html body describes the same scoped body, not a nested second body.
      const nodes = selector.nodes;
      const bodyIndex = nodes.findIndex((n, i) => i > 1 && n.type === 'tag' && n.value === 'body');
      if (bodyIndex >= 0 && nodes.slice(2, bodyIndex).every(n => n.type === 'combinator' && n.value.trim() === '')) {
        nodes.slice(2, bodyIndex + 1).forEach(n => n.remove());
      }
      const combinator = selector.nodes.find(n => n.type === 'combinator');
      if (combinator) {
        selector.insertBefore(combinator, selectorParser.combinator({value: ' '}));
        selector.insertBefore(combinator, selectorParser.className({value: 'elementor'}));
      }
      return;
    }
    // The source puts this class on <body>, not a descendant container.
    if (first?.type === 'class' && first.value === 'catalogue-page') {
      selector.prepend(selectorParser.className({value: 'annie-site'}));
      selector.prepend(selectorParser.tag({value: 'body'}));
      const combinator = selector.nodes.find(n => n.type === 'combinator');
      if (combinator) {
        selector.insertBefore(combinator, selectorParser.combinator({value: ' '}));
        selector.insertBefore(combinator, selectorParser.className({value: 'elementor'}));
      }
      return;
    }
    const whitespace = selector.first.spaces.before;
    selector.first.spaces.before = '';
    const leading = selectorParser().astSync(prefix + ' ').first.nodes;
    [...leading].reverse().forEach(n => selector.prepend(n.clone()));
    selector.first.spaces.before = whitespace;
  })).processSync(value);
}

function scopeCss(css) {
  const root = postcss.parse(css);
  root.walkRules(rule => {
    for (let parent = rule.parent; parent; parent = parent.parent) {
      if (parent.type === 'atrule' && /^(?:-\w+-)?keyframes$|^font-face$/i.test(parent.name)) return;
    }
    rule.selector = scopeSelector(rule.selector);
  });
  return root.toString();
}

function generate(root = path.resolve(__dirname, '..')) {
  const out = path.join(root, 'wp-plugin/annie-yahaya-site/assets/scoped');
  fs.mkdirSync(out, {recursive:true});
  const manifest = {};
  for (const name of ['styles.css','coaching.css','creations.css']) {
    const source = fs.readFileSync(path.join(root, 'reference', name));
    manifest[name] = crypto.createHash('sha256').update(source).digest('hex');
    fs.writeFileSync(path.join(out, name), '/* GENERATED by scripts/scope-css.cjs — do not edit. */\n' + scopeCss(source.toString('utf8')));
  }
  fs.writeFileSync(path.join(out, 'source-sha256.json'), JSON.stringify(manifest, null, 2) + '\n');
}
module.exports = {scopeCss, scopeSelector, generate};
if (require.main === module) generate();
